=== NCAR/lrose-docs/xml/schemas/tstorms.1.0.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:annotation>
    <xs:documentation>
    SCHEMA for TITAN STORMS XML format
    RAL, NCAR
    </xs:documentation>
  </xs:annotation>

  <xs:element name="tstorms">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="head"/>
        <xs:element ref="storm-data"/>
      </xs:sequence>
      <xs:attribute name="version" use="required" type="xs:decimal"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="head">
    <xs:complexType>
      <xs:all>
        <xs:element ref="system"/>
        <xs:element ref="title"/>
        <xs:element ref="product-description"/>
        <xs:element ref="time-coordinate"/>
        <xs:element ref="write-time"/>
      </xs:all>
    </xs:complexType>
  </xs:element>

  <xs:element name="system" type="xs:NCName"/>
  <xs:element name="title" type="xs:string"/>
  <xs:element name="product-description" type="xs:string"/>

  <xs:element name="time-coordinate" type="xs:NCName"/>
  <xs:element name="write-time" type="xs:dateTime"/>

  <xs:element name="storm-data">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="observation-time"/>
        <xs:element ref="dbz-threshold"/>
        <xs:element maxOccurs="unbounded" ref="storm"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="observation-time" type="xs:dateTime"/>
  <xs:element name="dbz-threshold" type="xs:decimal"/>

  <xs:element name="storm">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="instance"/>
      </xs:sequence>
      <xs:attribute name="ID" use="required" type="xs:integer"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="instance">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="time"/>
        <xs:element ref="location"/>
        <xs:element ref="storm-parameters"/>
      </xs:sequence>
      <xs:attribute name="relative-time" use="required" type="relative-time_enum"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="time" type="xs:dateTime"/>

  <xs:element name="relative-time" type="relative-time_enum"/>
  <xs:simpleType name = "relative-time_enum">
    <xs:annotation>
      <xs:documentation>
      relative-time indicates wether this is current data, forecast
      data or data from the past.
      </xs:documentation>
    </xs:annotation>
    <xs:restriction base = "xs:string">
      <xs:enumeration value = "history"/> 
      <xs:enumeration value = "current"/> 
      <xs:enumeration value = "forecast"/> 
    </xs:restriction>
  </xs:simpleType>

  <xs:element name="location">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="area"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="area">
    <xs:complexType>
      <xs:all>
        <xs:element ref="ellipse"/>
        <xs:element ref="polygon"/>
      </xs:all>
    </xs:complexType>
  </xs:element>

  <xs:element name="ellipse">
    <xs:complexType>
      <xs:all>
        <xs:element ref="moving-point"/>
        <xs:element ref="major_axis"/>
        <xs:element ref="minor_axis"/>
        <xs:element ref="orientation"/>
      </xs:all>
    </xs:complexType>
  </xs:element>

  <xs:element name="major_axis">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:decimal">
          <xs:attribute name="units" use="required" type="xs:NCName"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>

  <xs:element name="minor_axis">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:decimal">
          <xs:attribute name="units" use="required" type="xs:NCName"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>

  <xs:element name="orientation">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:double">
          <xs:attribute name="units" use="required"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>

  <xs:element name="polygon">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="moving-point"/>
        <xs:element ref="point" maxOccurs="73"/>
      </xs:sequence>
      <xs:attribute ref="npoints"/> 
    </xs:complexType>
  </xs:element>
  <xs:attribute name="npoints" type="xs:integer"/>

  <xs:element name="point">
    <xs:complexType>
      <xs:attribute name="latitude" use="required" type="xs:decimal"/>
      <xs:attribute name="longitude" use="required" type="xs:decimal"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="storm-parameters">
    <xs:complexType>
      <xs:all>
        <xs:element ref="ID_child" minOccurs="0"/>
        <xs:element ref="ID_parent" minOccurs="0"/>
        <xs:element ref="age"/>
        <xs:element ref="cell_top"/>
        <xs:element ref="max_dbz"/>
      </xs:all>
    </xs:complexType>
  </xs:element>

  <xs:element name="ID_child">
    <xs:complexType mixed="true">
      <xs:attribute name="units" use="required" type="xs:NCName"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="ID_parent">
    <xs:complexType mixed="true">
      <xs:attribute name="units" use="required" type="xs:NCName"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="age">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:integer">
          <xs:attribute name="units" use="required" type="xs:NCName"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>

  <xs:element name="cell_top">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:decimal">
          <xs:attribute name="units" use="required" type="xs:NCName"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>

  <xs:element name="max_dbz">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:decimal">
          <xs:attribute name="units" use="required" type="xs:NCName"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>

  <xs:element name="moving-point">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="latitude"/>
        <xs:element ref="longitude"/>
        <xs:element ref="polar_motion"/>
      </xs:sequence>
      <xs:attribute name="type" use="required" type="xs:NCName"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="latitude" type="xs:decimal"/>
  <xs:element name="longitude" type="xs:decimal"/>

  <xs:element name="polar_motion">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="speed"/>
        <xs:element ref="direction_to"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="speed">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:decimal">
          <xs:attribute name="units" use="required"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>

  <xs:element name="direction_to">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:decimal">
          <xs:attribute name="units" use="required"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== NCAR/lrose-docs/xml/examples/tstorms_example.xml
<?xml version="1.0" ?>
<tstorms xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.0" xsi:schemaLocation="http://www.ral.ucar.edu/xml/schemas/ http://www.ral.ucar.edu/xml/schemas/tstorms.1.0.xsd">
<head>
    <system>TITAN</system>
    <title>TITAN Thunderstorm Tracks</title>
    <product-description>TITAN on SAWS Radar mosaic</product-description>
    <time-coordinate>UTC</time-coordinate>
    <write-time>2008-01-26T02:14:58</write-time>
</head>
<storm-data>
  <observation-time>2008-01-04T00:00:00</observation-time>
  <dbz-threshold>35</dbz-threshold>
  <storm ID="2">
    <instance relative-time="current">
      <time>2008-01-04T00:00:00</time>
      <location>
        <area>
          <ellipse>
            <moving-point type="centroid">
              <latitude>-26.3117</latitude>
              <longitude> 29.7217</longitude>
              <polar_motion>
                <speed units="km h-1">27.133</speed>
                <direction_to units="degrees true">70.0176</direction_to>
              </polar_motion>
            </moving-point>
            <major_axis units="km">0.034208</major_axis>
            <minor_axis units="km">0.0258476</minor_axis>
            <orientation units="degrees true">158.234</orientation>
          </ellipse>
          <polygon npoints="73">
            <moving-point type="centroid">
              <latitude>-26.3117</latitude>
              <longitude> 29.7217</longitude>
              <polar_motion>
                <speed units="km h-1">27.133</speed>
                <direction_to units="degrees true">70.0176</direction_to>
              </polar_motion>
            </moving-point>
            <point latitude="-26.2751" longitude="29.7217" />
            <point latitude="-26.2750" longitude="29.7249" />
            <point latitude="-26.2917" longitude="29.7252" />
            <point latitude="-26.2917" longitude="29.7270" />
            <point latitude="-26.2917" longitude="29.7289" />
            <point latitude="-26.2916" longitude="29.7310" />
            <point latitude="-26.2917" longitude="29.7332" />
            <point latitude="-26.2917" longitude="29.7356" />
            <point latitude="-26.2916" longitude="29.7385" />
            <point latitude="-26.2916" longitude="29.7417" />
            <point latitude="-26.2948" longitude="29.7417" />
            <point latitude="-26.2977" longitude="29.7416" />
            <point latitude="-26.3001" longitude="29.7416" />
            <point latitude="-26.3023" longitude="29.7417" />
            <point latitude="-26.3044" longitude="29.7416" />
            <point latitude="-26.3063" longitude="29.7416" />
            <point latitude="-26.3081" longitude="29.7417" />
            <point latitude="-26.3085" longitude="29.7583" />
            <point latitude="-26.3117" longitude="29.7583" />
            <point latitude="-26.3149" longitude="29.7583" />
            <point latitude="-26.3181" longitude="29.7582" />
            <point latitude="-26.3215" longitude="29.7583" />
            <point latitude="-26.3250" longitude="29.7583" />
            <point latitude="-26.3250" longitude="29.7502" />
            <point latitude="-26.3250" longitude="29.7448" />
            <point latitude="-26.3256" longitude="29.7416" />
            <point latitude="-26.3285" longitude="29.7417" />
            <point latitude="-26.3317" longitude="29.7417" />
            <point latitude="-26.3355" longitude="29.7417" />
            <point latitude="-26.3403" longitude="29.7417" />
            <point latitude="-26.3416" longitude="29.7390" />
            <point latitude="-26.3417" longitude="29.7357" />
            <point latitude="-26.3416" longitude="29.7326" />
            <point latitude="-26.3417" longitude="29.7297" />
            <point latitude="-26.3416" longitude="29.7269" />
            <point latitude="-26.3418" longitude="29.7243" />
            <point latitude="-26.3417" longitude="29.7217" />
            <point latitude="-26.3418" longitude="29.7190" />
            <point latitude="-26.3416" longitude="29.7164" />
            <point latitude="-26.3417" longitude="29.7136" />
            <point latitude="-26.3416" longitude="29.7108" />
            <point latitude="-26.3417" longitude="29.7077" />
            <point latitude="-26.3416" longitude="29.7044" />
            <point latitude="-26.3417" longitude="29.7007" />
            <point latitude="-26.3417" longitude="29.6965" />
            <point latitude="-26.3417" longitude="29.6916" />
            <point latitude="-26.3368" longitude="29.6917" />
            <point latitude="-26.3327" longitude="29.6917" />
            <point latitude="-26.3290" longitude="29.6917" />
            <point latitude="-26.3257" longitude="29.6916" />
            <point latitude="-26.3166" longitude="29.7082" />
            <point latitude="-26.3152" longitude="29.7084" />
            <point latitude="-26.3140" longitude="29.7083" />
            <point latitude="-26.3128" longitude="29.7084" />
            <point latitude="-26.3117" longitude="29.7083" />
            <point latitude="-26.3105" longitude="29.7084" />
            <point latitude="-26.3093" longitude="29.7083" />
            <point latitude="-26.3081" longitude="29.7084" />
            <point latitude="-26.3068" longitude="29.7082" />
            <point latitude="-26.3055" longitude="29.7084" />
            <point latitude="-26.3040" longitude="29.7083" />
            <point latitude="-26.2907" longitude="29.6917" />
            <point latitude="-26.2865" longitude="29.6917" />
            <point latitude="-26.2816" longitude="29.6916" />
            <point latitude="-26.2759" longitude="29.6917" />
            <point latitude="-26.2749" longitude="29.6959" />
            <point latitude="-26.2751" longitude="29.7005" />
            <point latitude="-26.2750" longitude="29.7046" />
            <point latitude="-26.2750" longitude="29.7083" />
            <point latitude="-26.2751" longitude="29.7119" />
            <point latitude="-26.2751" longitude="29.7152" />
            <point latitude="-26.2750" longitude="29.7185" />
            <point latitude="-26.2751" longitude="29.7217" />
          </polygon>
        </area>
      </location>
      <storm-parameters>
        <age units="seconds">4200</age>
        <cell_top units="km">6.5</cell_top>
        <max_dbz units="dbz">44.5</max_dbz>
      </storm-parameters>
    </instance>
    <instance relative-time="forecast">
      <time>2008-01-04T00:30:00</time>
      <location>
        <area>
          <ellipse>
            <moving-point type="centroid">
              <latitude>-26.2699</latitude>
              <longitude> 29.8495</longitude>
              <polar_motion>
                <speed units="km h-1">27.133</speed>
                <direction_to units="degrees true">70.0176</direction_to>
              </polar_motion>
            </moving-point>
            <major_axis units="km">0.034208</major_axis>
            <minor_axis units="km">0.0258476</minor_axis>
            <orientation units="degrees true">158.234</orientation>
          </ellipse>
          <polygon npoints="73">
            <moving-point type="centroid">
              <latitude>-26.2699</latitude>
              <longitude> 29.8495</longitude>
              <polar_motion>
                <speed units="km h-1">27.133</speed>
                <direction_to units="degrees true">70.0176</direction_to>
              </polar_motion>
            </moving-point>
            <point latitude="-26.2333" longitude="29.8495" />
            <point latitude="-26.2333" longitude="29.8527" />
            <point latitude="-26.2499" longitude="29.8531" />
            <point latitude="-26.2499" longitude="29.8549" />
            <point latitude="-26.2500" longitude="29.8568" />
            <point latitude="-26.2499" longitude="29.8589" />
            <point latitude="-26.2500" longitude="29.8611" />
            <point latitude="-26.2500" longitude="29.8635" />
            <point latitude="-26.2499" longitude="29.8663" />
            <point latitude="-26.2499" longitude="29.8696" />
            <point latitude="-26.2531" longitude="29.8696" />
            <point latitude="-26.2560" longitude="29.8695" />
            <point latitude="-26.2584" longitude="29.8695" />
            <point latitude="-26.2606" longitude="29.8696" />
            <point latitude="-26.2627" longitude="29.8695" />
            <point latitude="-26.2646" longitude="29.8695" />
            <point latitude="-26.2664" longitude="29.8695" />
            <point latitude="-26.2667" longitude="29.8862" />
            <point latitude="-26.2699" longitude="29.8861" />
            <point latitude="-26.2731" longitude="29.8862" />
            <point latitude="-26.2764" longitude="29.8861" />
            <point latitude="-26.2797" longitude="29.8861" />
            <point latitude="-26.2833" longitude="29.8862" />
            <point latitude="-26.2832" longitude="29.8781" />
            <point latitude="-26.2833" longitude="29.8727" />
            <point latitude="-26.2839" longitude="29.8695" />
            <point latitude="-26.2867" longitude="29.8696" />
            <point latitude="-26.2900" longitude="29.8696" />
            <point latitude="-26.2938" longitude="29.8695" />
            <point latitude="-26.2986" longitude="29.8696" />
            <point latitude="-26.2999" longitude="29.8668" />
            <point latitude="-26.2999" longitude="29.8635" />
            <point latitude="-26.2998" longitude="29.8604" />
            <point latitude="-26.3000" longitude="29.8576" />
            <point latitude="-26.2998" longitude="29.8548" />
            <point latitude="-26.3000" longitude="29.8522" />
            <point latitude="-26.2999" longitude="29.8495" />
            <point latitude="-26.3000" longitude="29.8469" />
            <point latitude="-26.2998" longitude="29.8442" />
            <point latitude="-26.3000" longitude="29.8415" />
